version: '3'

services:
  backend1:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - PORT=3000
      - OTHER_SERVERS=http://backend2:3000,http://backend3:3000
    expose:
      - "3000"


  backend2:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - PORT=3000
      - OTHER_SERVERS=http://backend1:3000,http://backend3:3000
    expose:
      - "3000"


  backend3:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - PORT=3000
      - OTHER_SERVERS=http://backend1:3000,http://backend2:3000
    expose:
      - "3000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1
      - backend2
      - backend3